os: linux
dist: bionic
language: python
python:
  - "3.8"
jobs:
  fast_finish: true
  include:
    - python: "3.8"
      env: TOXENV=static
env:
  - TOXENV=unit
install:
  - pip install tox
script: tox
notifications:
  email: false